
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2015-12-01 17:14:28.963565
 ** by bitam@mahler
 ** MARKER_END
 **/

#include <srl.h>
#include <srl_private_types.h>



void hw_init()
{
}
