
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2015-11-24 17:11:41.413102
 ** by toumlilt@mahler
 ** MARKER_END
 **/

#include <srl.h>
#include <srl_private_types.h>



void hw_init()
{
}
