#!/usr/bin/env python
from dsx import *
from vgmn_noirq_multi import VgmnNoirqMulti
import sys

# Declaration of all MWMR fifos
tg_split        = Mwmr('tg_split'   , 32, 2)

split_demux1    = Mwmr('split_demux1'   , 32, 2)
split_demux2    = Mwmr('split_demux2'   , 32, 2)

demux_vld1  	= Mwmr('demux_vld1'  , 32, 2)
demux_vld2  	= Mwmr('demux_vld2'  , 32, 2)
vld_iqzz1   	= Mwmr('vld_iqzz1'   , 128, 2)
vld_iqzz2   	= Mwmr('vld_iqzz2'   , 128, 2)
iqzz_idct1  	= Mwmr('iqzz_idct1'  , 256, 2)
iqzz_idct2  	= Mwmr('iqzz_idct2'  , 256, 2)
idct_libu1  	= Mwmr('idct_libu1'  , 64, 2)
idct_libu2  	= Mwmr('idct_libu2'  , 64, 2)


huffman1    	= Mwmr('huffman1'    , 32, 2)
quanti1     	= Mwmr('quanti1'     , 64, 2)
huffman2    	= Mwmr('huffman2'    , 32, 2)
quanti2     	= Mwmr('quanti2'     , 64, 2)

libu_ramdac	= Mwmr('libu_ramdac', 48*8, 2)

tcg = Tcg(

    Task( 'tg', "tg",
          {'output':tg_split },
          defines = {'FILE_NAME':'"plan.mjpg"'}),
    
    Task( 'split', "split",
          { 'input':tg_split,
            'output0':split_demux1,
            'output1':split_demux2},
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),
    Task( 'demux1', "demux",
          { 'input':split_demux1,
            'output':demux_vld1,
            'huffman':huffman1,
            'quanti':quanti1 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),

    Task( 'demux2', "demux",
          { 'input':split_demux2,
            'output':demux_vld2,
            'huffman':huffman2,
            'quanti':quanti2 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),

    Task( 'vld1', "vld",
	  {'input':demux_vld1,
	   'output':vld_iqzz1,
	   'huffman':huffman1 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),
    

    Task( 'vld2', "vld",
	  {'input':demux_vld2,
	   'output':vld_iqzz2,
	   'huffman':huffman2 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),
    
    Task( 'iqzz1', "iqzz",
	  {'input':vld_iqzz1,
	   'output':iqzz_idct1,
	   'quanti':quanti1 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),
    
    Task( 'iqzz2', "iqzz",
	  {'input':vld_iqzz2,
	   'output':iqzz_idct2,
	   'quanti':quanti2 },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),

    Task( 'idct1', "idct",
	  {'input':iqzz_idct1,
	   'output':idct_libu1},
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),


    Task( 'idct2', "idct",
	  {'input':iqzz_idct2,
	   'output':idct_libu2},
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),

    Task( 'libu', "libu",
	  {'input0':idct_libu1,
	   'input1':idct_libu2,
	   'output':libu_ramdac},
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),

    Task( 'ramdac', "ramdac",
          { 'input': libu_ramdac },
            defines = {'WIDTH':"48",
                       'HEIGHT':"48"}),
    )

p = Posix()
tcg.generate(p)
